### ISSUE TITLE
Conque aplicación se puede visualizar los datos?

### ISSUE THREAD

**Issue by jasp402** [srbill1996/DrAbuseDB#1]
Hola, he intentado abrir los archivo bin y txt pero me sale distorsionado
![image](https://user-images.githubusercontent.com/8978470/88429485-5d3c4c80-cdbc-11ea-8c66-eaa084f63bb3.png)

**Comment by hwpoison** [comment]
La primera parte del archivo puede que se vea así luego comienza el texto plano, de lo contraio revisa el encode de tu visor de texto
